name: CI/CD Pipeline

on:
  push:
    branches:
      - release
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build app
        run: echo "Building application..."

  deploy_qa:
    name: Deploy to QA
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/release'
    needs: build
    environment:
      name: qa
    steps:
      - name: Deploy to QA
        run: echo "Deploying to QA environment..."

  deploy_prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build
    environment:
      name: prod
    steps:
      - name: Deploy to Production
        run: echo "Deploying to production..."
