name: CI/CD Pipeline

on:
  push:
    branches:
      - release
      - main

  pull_request:
    branches:
      - release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "BUILD OK"

  qa:
    if: github.event_name == 'push' && github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa
    steps:
      - run: echo "DEPLOY TO QA"

  prod:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: prod
    steps:
      - run: echo "DEPLOY TO PROD"

  pr-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR VALIDATION ONLY"
