name: Test QA Flow

on:
  push:
    branches:
      - release

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Building app..."

  deploy_qa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: qa
    steps:
      - run: echo "Deploying to QA..."
